name: CIPipeline
run-name: ${{ github.actor }} is running Github Actions
on:
  push:
    branches:
          - '**'        # matches every branch
          - '!main'     # excludes main branch
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '18.16.0'
      - name: Install modules
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Running Tests
        if: success() || failure()
        run: npm run GHtest

      - name: Check if there are any changes
        if: success() || failure()
        uses: stefanzweifel/git-auto-commit-action@v4

  Linter:
    runs-on: ubuntu-latest
    steps:

      - name: Repo History
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_INCLUDE: .*assets/.*
          FILTER_REGEX_EXCLUE: .*specs/.*
          DEFAULT_WORKSPACE: assets/
          DEFAULT_BRANCH: main
          LINTER_RULES_PATH: /
          CSS_FILE_NAME: .stylelintrc.json
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          IGNORE_GITIGNORED_FILES: true
          IGNORE_GENERATED_FILES: true
          VALIDATE_MARKDOWN: false
          VALIDATE_NATURAL_LANGUAGE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}