name: CICDPipeline
run-name: ${{ github.actor }} is running Github Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: npm run lint -- --fix
      - name: Setting Github user.email
        run: git config --global user.email ejoa@ucsd.edu
      - name: Setting Github user.name
        run: git config --global user.name "Elvis Joa"
      - name: Adding fixes for committing
        run: git add .
      - name: Committing ESLint fixes
        run: git commit -m "fixed ESLint issues"
      - name: Pushing fixes to current PR branch
        run: git push