name: CIPipeline
run-name: ${{ github.actor }} is running Github Actions
on:
  push:
    branches:
          - '**'        # matches every branch
          - '!main'     # excludes main branch
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '18.16.0'
      - name: Install modules
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Running Tests
        if: success() || failure()
        run: npm run GHtest