name: JestTesting
run-name: ${{ github.actor }} is running Github Actions
on:
  push:
    branches:
          - main     # Only runs on main
jobs:
  testing:
    runs-on: ubuntu-latest
    container: lironavon/docker-puppeteer-container:14.16.0
    env: 
      CI: true
    steps:
      - uses: actions/checkout@v3
      - name: Installing modules
        run: npm install
      - name: Running Tests
        run: npm test