name: JestTesting
run-name: ${{ github.actor }} is running Github Actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: npm run test