name: JestTesting
run-name: ${{ github.actor }} is running Github Actions
on:
  push:
    branches:
          - main     # Only runs on main
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Installing modules
        run: npm ci
        
      - name: Run Tests
        run: npm run GHtest
