name: JSDocs Generation And Test Coverage
run-name: ${{ github.actor }} is running Github Actions
on:
  push:
    branches:
          - main     # Only runs on main
  pull_request:
    branches:
          - main     # Only runs on main
permissions: write-all
jobs:
  JSDocs_Generation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Installing modules
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint
        
      - name: Generating JS Docs
        run: npm run doc
      
      - name: Pushing change
        uses: stefanzweifel/git-auto-commit-action@v4

  Test_Coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Installing modules
        run: npm ci

      - name: Running Tests
        if: success() || failure()
        run: npm run GHtest

      - name: Test Coverage
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          export CC_TEST_REPORTER_ID=${{secrets.CC_TEST_REPORTER_ID}}
          ./cc-test-reporter before-build
          ./cc-test-reporter after-build -t lcov